import ast
import ollama


def validate_code(code):
    """
    Validate Python code generated by the Developer Agent.
    """

    if not isinstance(code, str):
        raise ValueError("Generated code must be a string.")

    if not code.strip():
        raise ValueError("Generated code must not be empty.")

    try:
        tree = ast.parse(code)
    except SyntaxError as error:
        raise ValueError(
            f"Generated code is not valid Python: {error}"
        )

    functions = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef)
    ]

    if not functions:
        raise ValueError(
            "Generated code must contain at least one function."
        )

    return code


def run_developer(plan):
    """
    Generate Python navigation logic from a validated plan.
    """

    system_prompt = """
You are a Developer Agent.

Your task is to convert a validated robot navigation plan into
working Python code.

Follow these rules strictly:

1. Return ONLY Python source code.
2. Do not include markdown.
3. Do not include ```python code fences.
4. Do not include explanations before or after the code.
5. The generated program must contain at least one function
   implementing robot navigation logic.
6. The navigation logic may return only:
   FORWARD
   LEFT
   RIGHT
   STOP
7. The robot must never move into a blocked direction.
8. If no safe direction exists, the robot must return STOP.
9. Prefer movement toward the goal when that direction is safe.
   If the goal direction is blocked, choose another unblocked direction.
   Do not return STOP while a safe direction exists, unless the goal
   has already been reached.
10. Do not use external packages.
11. The generated file must be valid executable Python code.

The navigation function should take information about:
- whether front is blocked
- whether left is blocked
- whether right is blocked
- the direction of the goal

and return one of:
FORWARD, LEFT, RIGHT, STOP

Implement the decision in this order:
1. Build a list of unblocked actions from FORWARD, LEFT, RIGHT.
2. If the list is empty, return STOP.
3. Normalize goal_direction to uppercase. If it is in the list, return it.
4. Otherwise return the first action in the list.
Never return an action without checking its own blocked flag.
"""

    response = ollama.Client(timeout=120).chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": str(plan)
            }
        ],
        think=False,
        options={
            "temperature": 0,
            "num_predict": 1024,
        },
    )

    code = response["message"]["content"].strip()

    # Remove code fences if the model adds them accidentally
    if code.startswith("```python"):
        code = code[len("```python"):]

    if code.startswith("```"):
        code = code[3:]

    if code.endswith("```"):
        code = code[:-3]

    code = code.strip()

    return validate_code(code)
