import json
import ollama


VALID_ACTIONS = {"FORWARD", "LEFT", "RIGHT", "STOP"}


def validate_plan(data):
    """
    Validate the navigation plan generated by the Planner Agent.
    """

    if not isinstance(data, dict):
        raise ValueError("Plan must be a dictionary.")

    required_keys = {
        "strategy",
        "decisions",
        "stop_condition"
    }

    if set(data.keys()) != required_keys:
        raise ValueError(
            "Plan must contain exactly these keys: "
            "strategy, decisions, stop_condition"
        )

    if not isinstance(data["strategy"], str):
        raise ValueError("strategy must be a string.")

    if not isinstance(data["decisions"], list):
        raise ValueError("decisions must be a list.")

    if not isinstance(data["stop_condition"], str):
        raise ValueError("stop_condition must be a string.")

    if len(data["decisions"]) == 0:
        raise ValueError("decisions must not be empty.")

    for decision in data["decisions"]:
        if not isinstance(decision, dict):
            raise ValueError("Each decision must be a dictionary.")

        if set(decision.keys()) != {"condition", "action"}:
            raise ValueError(
                "Each decision must contain exactly "
                "condition and action."
            )

        if not isinstance(decision["condition"], str):
            raise ValueError("decision condition must be a string.")

        if decision["action"] not in VALID_ACTIONS:
            raise ValueError(
                f"Invalid action: {decision['action']}. "
                "Allowed actions are FORWARD, LEFT, RIGHT, STOP."
            )

    return data


def run_planner(requirement):
    """
    Generate and validate a navigation plan from requirements.
    """

    system_prompt = """
You are a Planner Agent for a mobile robot navigation system.

Your task is to receive validated software requirements from
an Analyst Agent and create a concrete navigation plan.

The Analyst Agent decides WHAT the software must achieve.
You decide HOW the software should behave.

Follow these rules strictly:

1. Return ONLY valid JSON.
2. Do not include markdown.
3. Do not include explanations outside the JSON.
4. Do not include code fences.
5. Do not add information that contradicts the requirements.
6. The robot may only use these actions:
   FORWARD
   LEFT
   RIGHT
   STOP
7. Never plan movement into a blocked direction.
8. Prefer movement toward the goal when that direction is safe.
9. If no safe movement direction exists, use STOP.
10. The JSON must contain exactly these keys:
    strategy
    decisions
    stop_condition

"strategy" must be a string describing the navigation strategy.

"decisions" must be a list of objects. Each object must contain:
- condition: a string
- action: one of FORWARD, LEFT, RIGHT, STOP

"stop_condition" must be a string describing when the robot stops.

Required output structure:

{
  "strategy": "string",
  "decisions": [
    {
      "condition": "string",
      "action": "FORWARD"
    }
  ],
  "stop_condition": "string"
}
"""

    response = ollama.chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": json.dumps(requirement)
            }
        ],
        format="json",
        options={
            "temperature": 0
        }
    )

    json_text = response["message"]["content"]

    plan = json.loads(json_text)

    validated_plan = validate_plan(plan)

    return validated_plan